### ISSUE TITLE
Is there support for textareas?

### ISSUE THREAD

**Issue by graciano** [brutusin/json-forms#10]
I couldn't find any example in [the demo](http://brutusin.org/json-forms/) of a field that is rendered as a textarea. If there isn't, can I try to add it?

*PS.: this is awesome. Congratulations, I loved this package.*

**Comment by idelvall** [comment]
Hello Graciano, thanks for your kind words.
Out of the box, the library renders as textareas only data with schema of type "any"
```
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "any"
}
```
in these cases, the value of the generated textarea must evaluate to a valid JSON expression.

If you want to render data of type "string" as textareas, I can give an example of how to do it, using a specific schema "format"

**Comment by graciano** [comment]
Thanks, it's solved.

**Comment by idelvall** [comment]
Hello @graciano, maybe this new feature is of your interest: https://github.com/brutusin/json-forms/issues/17
Cheers

**Comment by graciano** [comment]
Sure, it's more semantic and clear :+1:
