### ISSUE TITLE
Textarea input type

### ISSUE THREAD

**Issue by fj7** [brutusin/json-forms#17]
How can I use a normal HTML textarea in my form? In the schema I can use the "any" type and it renders a tertarea but the value part is JSON and not string.

**Comment by idelvall** [comment]
I thought i would be easier using `BrutusinForms.addDecorator(f(htmlElement, schema))` but finally added into the main script a modification for supporting `"format":"text"` in `string` schemas and rendering with a textarea if present.

**Comment by idelvall** [comment]
So since version `1.3.0` you can use this `text` format to render the field as a `textarea`.
Example:
```javascript
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "string",
  "format": "text"
}
```

**Comment by fj7** [comment]
Perfect. Thank you.

**Comment by araneta** [comment]
how to set the textarea value?
