### ISSUE TITLE
Can I use this in Angular2?

### ISSUE THREAD

**Issue by estradamarkie** [brutusin/json-forms#38]
Is there a way to use this in angular2?

I tried doing something like `var Brutusin = require('json-form')` but not sure if this is how I can import it in my application.

Thanks,

**Comment by idelvall** [comment]
Hi, yes it can be done.
I am waiting for a coworker response it this matter (he has used it with Angular 2). 
I will let you know 
Cheers

**Comment by estradamarkie** [comment]
Yes please, as separating this lib away from angular makes me wanna cry :( as atm have to use `iframe` just to render the forms in my angular app. Would be nice if it can be imported :)

**Comment by estradamarkie** [comment]
To add, does the plugin currently support `$ref` ?

**Comment by idelvall** [comment]
Sorry man, it was Angular 1, and I do not know either of them.
Nevertheless, this google search gives promising results: https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=angular+2+external+js

If you get some conclusions from all of this, please tell me, so I can improve the documentation. 

Also, feel free to fork the project and send me a pull request if some coding is needed (for example for creating a module for Angular 2)

**Comment by estradamarkie** [comment]
Sure, I've been trying tbh. Is the plugin available on npm by any chance?

**Comment by idelvall** [comment]
I'am afraid is not. We have an open issue, maybe you can help with it: https://github.com/brutusin/json-forms/issues/12
