### ISSUE TITLE
how to style the form?

### ISSUE THREAD

**Issue by estradamarkie** [brutusin/json-forms#39]
I want to style the form using bootstrap form style, the out of the box form is pretty standard and not styled. I want to make it similar to the demo version, how can I style it?

Thanks

**Comment by idelvall** [comment]
Hi, 
You can customize the style sheet https://github.com/brutusin/json-forms/blob/master/src/css/brutusin-json-forms.css

**Comment by estradamarkie** [comment]
Oh right, thought its using a standard bootstrap. Thanks :)

Not sure if you've seen my other ticket, re Angular2 just wondering if this can be imported on angular2.
