### ISSUE TITLE
Does it support $ref?

### ISSUE THREAD

**Issue by estradamarkie** [brutusin/json-forms#40]
I have $refs in my data though some are nested, just wondering if the plugin does support `$ref : { #/defintion/obj }` even if some are nested (data is coming from Swagger)? If so can you tell me how its being done or its processing it automatically?

I'm doing an ajax call to my swagger json to grab the schema.

Sample JSON
```javascript
{
  "Name": {
    "type": "string"
  },
  "Number": {
    "format": "int32",
    "type": "integer"
  },
  "PointInTime": {
    "format": "date-time",
    "type": "string"
  },
  "Url": {
    "type": "string"
  },
  "Children": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/TestSimpleInputChild"
    }
  },
  "CustomData": {
    "type": "object",
    "additionalProperties": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}`
```

**Comment by idelvall** [comment]
http://brutusin.org/json-forms/#11

**Comment by estradamarkie** [comment]
Yeah saw that but seems like it only accept $ref within the same schema, what if its outside. Like the example above, `TestSimpleInputChild` is outside that JSON or do I have to manually map it :(

**Comment by idelvall** [comment]
You need to add the definitions property to the schema object before rendering the form

**Comment by estradamarkie** [comment]
Sorry I don't follow, can you slow an example using the schema above?

**Comment by idelvall** [comment]
You need to create an schema object similar to that used in the example http://brutusin.org/json-forms/#11
If you have the definitions outside, you need to include them inside the schema

**Comment by BredStik** [comment]
http://brutusin.org/json-forms/#11 this sample doesn't work anymore, any clue why?
