### ISSUE TITLE
Is it possible to add Id on the form?

### ISSUE THREAD

**Issue by estradamarkie** [brutusin/json-forms#41]
Hi,

Is it possible to add an `id` to the form or `tr` element? adding the object name like `Name` so it can be hidden/show using `checkbox`?

So I can do something similar to this.
https://jsfiddle.net/z_acharki/jnwrc5ay/216/

**Comment by idelvall** [comment]
For the form you can do this directly in its parent container (where you render it)
For  the `tr` you can decorate the object to be renderer using `BrutusinForms.addDecorator` (see https://github.com/brutusin/json-forms#api)

**Comment by estradamarkie** [comment]
I meant I'm planning to put the checkbox in a separate panel/screen so it acts as its a setting of the form.

Can you show an example from the `form`?

**Comment by idelvall** [comment]
what exactly do you want to hide/show?

**Comment by estradamarkie** [comment]
for example, I want to hide e.g Name or some objects in the `Children`. Its to allow a user to hide/show whatever object they want basically, as not all of the objects are required to submit the form.

```javascript
{
  "Name": {
    "type": "string"
  },
  "Number": {
    "format": "int32",
    "type": "integer"
  },
  "PointInTime": {
    "format": "date-time",
    "type": "string"
  },
  "Url": {
    "type": "string"
  },
  "Children": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/TestSimpleInputChild"
    }
  },
  "CustomData": {
    "type": "object",
    "additionalProperties": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  }
}`
```

**Comment by idelvall** [comment]
Ok, I understand, let me think on it

**Comment by estradamarkie** [comment]
Cool thanks,

**Comment by estradamarkie** [comment]
actually any update on this? :)

**Comment by idelvall** [comment]
Sorry man, I forgot the issue. I am working to give you an answer today

**Comment by idelvall** [comment]
If have made some minor changes [v1.5.3](https://github.com/brutusin/json-forms/releases/tag/v1.5.3)  that make possible to use decorators to achieve this:

```javascript
BrutusinForms.addDecorator(
     function (element, schema) {
        if (element.tagName) {
            var tagName = element.tagName.toLowerCase();
            if (tagName === "tr") {
                element.id="tr_"+schema.$id;
            }
         }
    }
);
```

This is just an example. Be aware that depending on your schema these ids may be repeated (so you need to handle it); for example for properties of an array...

**Comment by estradamarkie** [comment]
Is it possible to add custom `class` on `textarea` like `input_id` so I can get the value of each `input`. I know there's a submit function but that's returning me a JSON format which isn't really necessary for my need.

I tried the code below but that didn't work or do I have to do it separately? 

```
if (element.tagName) {
            var tagName = element.tagName.toLowerCase();
            if (tagName === "tr" && tagName ==="textarea" ) {
                element.className="tr_"+schema.$id;
            }
         }
```

**Comment by estradamarkie** [comment]
Nvm about my last comment, I've solved it.

Thanks.
