### ISSUE TITLE
Some suggestions about Brutusin json form

### ISSUE THREAD

**Issue by francocaruso** [brutusin/json-forms#44]
Hi guys,
I recently found your very great works, Json form, it is so flexible and easy to use.
It is very suitable for me, but I think if something will be enhanced(or just I don't know how to use it correctly), it could be much flexible. Many thanks to Mr. Ignacio del Valle Alles and all that contribute to the project.
1. More clear documents to be supported, I will offer some code as example I guess.
2. How to externally set a value by column on Schema Resolver module and customized error message to a certain column of form properties and user defined validation function on submition?
Ex.
```javascript
bf.schemaResolver = function (names, data, cb) {
    var schemas = new Object();
    var schema = new Object();
    if (data.user_password1 != '' && data.user_password2 != '' && data.user_password1 === data.user_password2) {
    } else {
        BrutusinForms.user_password.addError("Re-enter password, please!"); // Sample
    }
	schema.title = "Confirm Password";
	schema.type = "string";
	schema.value = data.user_password1; // Failed
	schema.readOnly = true; // Failed
	schema.required = true; // Failed
	schema.value = "TEST"; // Failed        
	schemas[names] = schema;
	setTimeout(function(){cb(schemas)},100); // in order to show asynchrony
};    
```             
3. I made some modification to your code, and I feedback to you as the attachment.
a. Seperate each enum item to {'value':'dog', 'text': 'Dog'}
b. Some multilingual issues.
c. provide zh_CN(Simplified Chinese) and zh_TW (Traditional Chinese) language files.
[brutusin-json-forms-bootstrap.js.txt](https://github.com/brutusin/json-forms/files/635765/brutusin-json-forms-bootstrap.js.txt)
[brutusin-json-forms-bootstrap.js.txt](https://github.com/brutusin/json-forms/files/635766/brutusin-json-forms-bootstrap.js.txt)
[brutusin-json-forms-lang-en_US.js.txt](https://github.com/brutusin/json-forms/files/635767/brutusin-json-forms-lang-en_US.js.txt)
[brutusin-json-forms-lang-zh_TW.js.txt](https://github.com/brutusin/json-forms/files/635769/brutusin-json-forms-lang-zh_TW.js.txt)
[brutusin-json-forms-lang-zh_CN.js.txt](https://github.com/brutusin/json-forms/files/635768/brutusin-json-forms-lang-zh_CN.js.txt)
[brutusin-json-forms.js.txt](https://github.com/brutusin/json-forms/files/635770/brutusin-json-forms.js.txt)

**Comment by idelvall** [comment]
I Franco, some questions here:
Regarding:
1. Please give us examples of what you mean.
2. What you are trying to achieve? Share also the root schema
3. As an attachment the modifications are very difficult to inspect and merge. The standard procedure is preferred that is: fork the project, commit and push your changes, and send us a pull request. More info here https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

Thanks!
