### ISSUE TITLE
Don't see the form on IE 11

### ISSUE THREAD

**Issue by estradamarkie** [brutusin/json-forms#46]
Hi,

Just wondering if the plugin supports IE 11? I'm not seeing the form on IE 11 at all however it works on the browsers including Edge. Also I get an error which I'm not sure if its part of it.

![image](https://cloud.githubusercontent.com/assets/17979376/21135683/a4bfd584-c11a-11e6-9747-99e329a4793e.png)
![image](https://cloud.githubusercontent.com/assets/17979376/21136043/f139df58-c11b-11e6-9722-c573ff7dfdb1.png)

**Comment by idelvall** [comment]
can you see the demo forms? 
http://brutusin.org/json-forms/

I can with IE `11.0.9600.18015`

**Comment by estradamarkie** [comment]
Yeah I can see it on IE, strange as I can't see my form on IE but its working fine on others. I get JSON string as I had to do something with `$ref` because some objects are being referenced outside the object. So I get a massive JSON string then I `JSON.parse()` that string, but I don't see that as a reason for the form to not work on IE.

The images above are the only error I can see on the console.

function generateFormRequest(schema) {
    var BrutusinForms = brutusin["json-forms"];
    bf = BrutusinForms.create(schema); // schema is the JSON parsed
    var container = document.getElementById('jsonSchemaForm');
    bf.render(container);
}

My current IE version
![image](https://cloud.githubusercontent.com/assets/17979376/21141225/edc60762-c133-11e6-8f8b-15dcb503b109.png)

**Comment by estradamarkie** [comment]
this is on windows 10, not sure if that's relevant but thought I will mention it anyway.

**Comment by idelvall** [comment]
can you share a JSFiddle reproducing the problem?

**Comment by estradamarkie** [comment]
@idelvall Hi, sorry took me quite a while to get back.

Here's a fiddle sample https://jsfiddle.net/cdag8q4g/1/, I can't see my form on my current IE version.

**Comment by estradamarkie** [comment]
@idelvall I'm not sure if this is correct, but it seems like the `date` that's causing this issue. Can you confirm this please.

**Comment by idelvall** [comment]
confirmed, thanks for the feedback. fixing it...

**Comment by estradamarkie** [comment]
It doesn't seems to have the option to pick a date, it's just showing a plain text field.

**Comment by idelvall** [comment]
Yes, but at least it works. Maybe we can add a polyfill instead...

**Comment by estradamarkie** [comment]
Will the polyfill be added in the fix?

**Comment by idelvall** [comment]
After thiking about it, I don't like the idea of including the pollyfix inside this library. In any case you can decorate the input according to your needs (see an example decorator [here](https://github.com/brutusin/json-forms/blob/master/src/js/brutusin-json-forms-bootstrap.js#L56))

**Comment by idelvall** [comment]
More examples here http://brutusin.org/json-forms/#9
