### ISSUE TITLE
Cannot load "Additional properties" with initial data

### ISSUE THREAD

**Issue by vinayak-mehta** [brutusin/json-forms#48]
When I try to load http://brutusin.org/json-forms/#6 with the following data, 

<pre>
{
  "fixed": {
    "field1": {
      "name": "foo",
      "age": "bar"
    }
  },
  "free": {
    "field2": "baz"
  }
}
</pre>

it gives the following error.

![](http://i.imgur.com/N4AACfj.png)

Is this a known bug or am I doing something wrong?

**Comment by idelvall** [comment]
It's a new bug. I am looking into it
Thanks!

**Comment by idelvall** [comment]
Fixing release: [v1.4.1](https://github.com/brutusin/json-forms/releases/tag/v1.4.1)
