### ISSUE TITLE
Support for optional booleans

### ISSUE THREAD

**Issue by dnault** [brutusin/json-forms#50]
Currently if the schema has a boolean property, the generated form is the same regardless of whether the property is marked as `required: false`, and the data from the form always has the boolean property with a value of either `true` or `false`.

What I'd like is for there to be a way to specify that a boolean is optional (nullable), such that the user can opt not to set a value.

One possible solution for optional booleans would be to use a menu with ("(blank)", "true", "false") instead of a checkbox.

**Comment by idelvall** [comment]
it make sense, working on it...

**Comment by idelvall** [comment]
fixed!

**Comment by dnault** [comment]
Awesome! Happy New Year!
