### ISSUE TITLE
I need an example JSON submit Form POST

### ISSUE THREAD

**Issue by eloaders** [brutusin/json-forms#54]
Is it possible to use JSON in a form that can send using the POST method to the server? And create a form using GET?

**Comment by idelvall** [comment]
Sorry but I don't understand what you need, and how it is related to this library

**Comment by eloaders** [comment]
I want create a FORM using JSON file format which DATA stored in JSON file will be sent via POST method to SERVER.

**Comment by idelvall** [comment]
yes it is possible, once you obtain the JSON data from the form generated by the library (obtained from a JSON Schema that you specify) you can do whatever you want with it in javascript, from example sending its [JSON representation](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/JSON/stringify) using another form under your control, via AJAX, or websockets
