### ISSUE TITLE
onValidationError alert

### ISSUE THREAD

**Issue by vincentmorneau** [brutusin/json-forms#58]
I believe `bf.validate()` https://github.com/brutusin/json-forms/blob/master/src/js/brutusin-json-forms.js#L103 could return a JSON object with the message instead of forcing an alert. 

Example:
```javascript
var validation = bf.validate();
if (!validation.success)
   console.log(validation.message); // then we can choose what to do with the message
```

What do you think?

**Comment by idelvall** [comment]
Hi, this is just the default implementation. You can override the handler by setting your own
```
BrutusinForms.onValidationError = function (element, message) {
        element.focus();
        if (!element.className.includes(" error")) {
            element.className += " error";
        }
        alert(message);
    };
```

**Comment by vincentmorneau** [comment]
Sounds good! Closing this.
