### ISSUE TITLE
Add multi-select functionality

### ISSUE THREAD

**Issue by tejovanthn** [brutusin/json-forms#71]
In the enum fields, I thought we could use a field like `multiple = true` to make the select field into a multi-select checkbox. 

The change will need to include
``` 
if (s.multiple){
    input.multiple = true;
}
```
while handling the `s.enum` case in `renderers["string"]`

And
```
 if (schema.enum) {
     if(input.multiple){
         value = Array.from(input.options).reduce(function(acc, el){
                 if(el.selected){acc.push(el.textContent);}
                 return acc;
                 },[]).join(",");
     }   
     else{
         value = input.options[input.selectedIndex].value;
     }   
 }

```
while handling `getValue` to save the selected values (hacky).

**Comment by idelvall** [comment]
Hi, @tejovanthn .
Given that this is not a standard feature, i can't integrate it into the main code, nevertheless, you can extend the library to support it without needing to integrate it into the code, by adding a custom decorator.

For custom decorator examples see :
* https://github.com/brutusin/json-forms#static-members
* http://brutusin.org/json-forms/#9
