### ISSUE TITLE
postRender problem?

### ISSUE THREAD

**Issue by fabifabi** [brutusin/json-forms#74]
postRender is not call if we do "addItem" in a tab....is it normal?

**Comment by idelvall** [comment]
hi, what do you mean by "a tab"?
Can you create a JSFiddle to reproduce the problem?

**Comment by fabifabi** [comment]
an array, sorry for my french ^^

**Comment by fabifabi** [comment]
two solution : postRender is call when it geenrate a new cell of my array (when user click on "add item") OR more easy, put a class "additem" on the button, as it,i can know a new rendering was done ?

**Comment by idelvall** [comment]
postRender is called once, when the form is rendered. 

Use a decorator instead. 

https://github.com/brutusin/json-forms#static-members
