### ISSUE TITLE
i18n true/false

### ISSUE THREAD

**Issue by fabifabi** [brutusin/json-forms#75]
line 358/364

The title is enough i think? ;)

**Comment by idelvall** [comment]
Thanks fabi, i'll change it.
It would be great if you  will send your suggestions as [pull requests](https://yangsu.github.io/pull-request-tutorial/)

**Comment by fabifabi** [comment]
Sorry,i have a github account just for your library in fact,i am very new
here :)
thanks for your work, and my article for french magazine is ready, i will
send you a pdf after it is publish !

2017-03-30 9:25 GMT+02:00 Ignacio del Valle Alles <notifications@github.com>
:

**Comment by idelvall** [comment]
dont get me wrong, i am grateful to you for your suggestions, but its woth your time learning how to use these techniques.
I am looking forward to see that article!

**Comment by idelvall** [comment]
Can you give the translations to french?
```javascript
 BrutusinForms.messages = {
        "validationError": "Validation error",
        "required": "This field is **required**",
        "invalidValue": "Invalid field value",
        "addpropNameExistent": "This property is already present in the object",
        "addpropNameRequired": "A name is required",
        "minItems": "At least `{0}` items are required",
        "maxItems": "At most `{0}` items are allowed",
        "pattern": "Value does not match pattern: `{0}`",
        "minLength": "Value must be **at least** `{0}` characters long",
        "maxLength": "Value must be **at most** `{0}` characters long",
        "multipleOf": "Value must be **multiple of** `{0}`",
        "minimum": "Value must be **greater or equal than** `{0}`",
        "exclusiveMinimum": "Value must be **greater than** `{0}`",
        "maximum": "Value must be **lower or equal than** `{0}`",
        "exclusiveMaximum": "Value must be **lower than** `{0}`",
        "minProperties": "At least `{0}` properties are required",
        "maxProperties": "At most `{0}` properties are allowed",
        "uniqueItems": "Array items must be unique",
        "addItem": "Add item",
        "true": "True",
        "false": "False"
    };
```

**Comment by fabifabi** [comment]
i will do it,no problem....but still not an GIT expert,so i will post it
here....
sorry the articles is long,i can't translate to english.
for resume, it is introduction to json schema first. how to validate data
in back end (using node.js) and how to generate/validate the form in front
using your library.

2017-03-30 9:50 GMT+02:00 Ignacio del Valle Alles <notifications@github.com>
:

**Comment by idelvall** [comment]
fixed

**Comment by fabifabi** [comment]
BrutusinForms.messages = {
        "validationError": "Erreur de validation",
        "required": "Ce champ est **obligatoire**",
        "invalidValue": "Valeur du champ invalide",
        "addpropNameExistent": "Cet propriété est déjà présente dans l'objet",
        "addpropNameRequired": "Un nom est obligatoire",
        "minItems": "Au moins `{0}` éléments sont requis",
        "maxItems": "Au plus `{0}` élément sont autorisés",
        "pattern": "La valeur n'est pas conforme au patron: `{0}`",
        "minLength": "La valeur doit être **au moins**  de `{0}` caractères",
        "maxLength": "La valeur doit être **au maximum* de `{0}`  caractères",
        "multipleOf": "La valeur doit être **multiple** de `{0}`",
        "minimum": "La valeur doit être **supérieur ou égale**  à `{0}`",
        "exclusiveMinimum": "La valeur doit être  **supérieur** à `{0}`",
        "maximum": "La valeur doit **inférieur ou égale** à`{0}`",
        "exclusiveMaximum": "La valeur doit être **inférieur** à `{0}`",
        "minProperties": "Au moins `{0}` propriétés sont obligatoire",
        "maxProperties": "Au plus `{0}` propriétés sont autorisés",
        "uniqueItems": "Les éléments du tableaux doivent être unique",
        "addItem": "Ajouter un élément",
        "true": "Vrai",
        "false": "Faux"
    };
