### ISSUE TITLE
"any" type properties are never valid

### ISSUE THREAD

**Issue by joguiMultimedia** [brutusin/json-forms#81]
Using the the "Simple" example and changing the property type to "any" displays a textarea control which is OK. As long as the input is empty the validation passes but inserting any text/number throws a validation error.
Is this the intent? what content should be entered in "any" field?

```javascript
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "title": "A boolean",
  "description": "A simple boolean data type as schema root",
  "type": "any"
}
```

**Comment by joguiMultimedia** [comment]
EDIT: adding double quotes passes the validation. single quotes no.
Maybe a parsing artefact?

**Comment by idelvall** [comment]
Hi @joguiMultimedia. I can't reproduce the issue. What dta are you inputing? What browser are you using?

**Comment by joguiMultimedia** [comment]
using chrome/chromium.
any text is invalid unless surrounding it with double quotes.
Maybe chrome textarea have a strange way of returning the data...

**Comment by joguiMultimedia** [comment]
reproduced with firefox 53.0 as well.

**Comment by joguiMultimedia** [comment]
When using initial data to fill the field, the textarea content shows the quotes.

**Comment by idelvall** [comment]
that is the expected behaviour. "any" here mens any schema type (number, boolean, object, array...), not any string. The value to enter in the text area must be a valid JSON expression

**Comment by joguiMultimedia** [comment]
OK, I got it.
I will use a decorator to enter a free text, arbitrarily sized in a textarea. Unless there is another preexisting solution?

**Comment by joguiMultimedia** [comment]
Thanks for quick reply.

**Comment by idelvall** [comment]
Yes, thereis a better way for this. http://brutusin.org/json-forms/#8

**Comment by joguiMultimedia** [comment]
I missed that. thanks.
