### ISSUE TITLE
getData() doesn't return boolean fields

### ISSUE THREAD

**Issue by Klickmichel** [brutusin/json-forms#83]
In the returning json from getData() all boolean properties are missing.
I don't thinks it's a problem with my implementation because it is the same behaviour in your demo: http://brutusin.org/json-forms/#1
Predefined example "Simple" returns "null"

**Comment by idelvall** [comment]
Soved in src. Pending generating dist files...
Thanks!

**Comment by idelvall** [comment]
https://github.com/brutusin/json-forms/releases/tag/v1.6.3

**Comment by Klickmichel** [comment]
Thanks for the fast fixing 👍
