### ISSUE TITLE
readOnly and default is not available at item of array 

### ISSUE THREAD

**Issue by baixiyang** [brutusin/json-forms#84]

**Comment by idelvall** [comment]
can you provide an example?

**Comment by baixiyang** [comment]
it did well  in http://brutusin.org/json-forms/，but failed in master code 。here is my test data
{
    "type": "array",
    "items":{
        "type":"object",
        "properties":{
            "a":{
                "type":"string",
                "readOnly":true,
                "default":"asdf"
            }
        }
    }
}

**Comment by idelvall** [comment]
you need to specify initial data

**Comment by idelvall** [comment]
I see your point, using "default"... I will work on it

**Comment by idelvall** [comment]
As far as i can see, it's working properly.
Maybe you are inputting invalid initial data?

**Comment by baixiyang** [comment]
I debug to this line, initialValue is an empty object. but in  http://brutusin.org/json-forms/  initialValue is null.
if (typeof initialValue !== "undefined" && initialValue !== null) {
          value = getInitialValue(id);
} else {
          value = s.default;
 }

**Comment by baixiyang** [comment]
oh ，I  knew the reason ,because I pass an initial data
bf.render(container, {});

**Comment by baixiyang** [comment]
I'm sorry to trouble you ， thank you so much!

**Comment by idelvall** [comment]
no trouble at all!
