### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by fabifabi** [brutusin/json-forms#88]
line 177:
if (s.media) {
                input = document.createElement("input");
                input.type = "file";
                appendChild(container, input, s);
                // XXX TODO, encode the SOB properly.
            }

**Comment by fabifabi** [comment]
line 345:
            if (s.required) {
                input = document.createElement("input");
                input.type = "checkbox";
                if (value === true) {
                    input.checked = true;
                } else if (s.default !== undefined)
                {
                    input.checked = s.default;
                }
            }

**Comment by fabifabi** [comment]
line 753:             addButton.className = "addItem";
I need this for know where it is on the form. as it ,i cna customize the table edition (i put up/down as a decorator, so i can move my item in the table)

**Comment by idelvall** [comment]
thanks @fabifabi

**Comment by fabifabi** [comment]
Hello!

I added "up" and "down" button to array renderer.As it u can move up&down your item,that's can be usefull (at least for me,lol)... I will do the decorator for  bootstrap.
My (little) problem:
I am very bad for git :) so i do'nt know how to post it for you.....
As it is arround 40 lines,can i post it here ?
Or can i have an email to post it ?

Thanks a lot,i love your work,men !

**Comment by idelvall** [comment]
:) you should definitely invest some time in learning git basics, it's worth it.
You can create a fiddle to share the code and at the same time show these new feature.
Thanks @fabifabi you rock!

**Comment by fabifabi** [comment]
I am using GIT but i dont know how that's work with github :) the bootstrap is done also....i will try do a branch for show you it, i think it is bug free....and it is mroe hard to do with decorator than inside the original source......okay,let's me try this {#|[{#|{[ git :)

**Comment by fabifabi** [comment]
my demo : http://www.pigere.com/demojson/

The source are not minify,so u can take :)

I tried to publish on github,but i am fear to publish all my git...and i am not in mood to read all tutotiral for today,sorry, kinda lazy for learn tool.i prefer code more than learn it hahaha!

**Comment by fabifabi** [comment]
ho i forgot my sample is in french,so for see how that's work on a normal example, go "liste menbre" panel,try add (you add people),and move them up&down&remove.
thanks,hope thats' help a bit for this fantastic library.

**Comment by idelvall** [comment]
Yes I see, that is a useful feature.
I will include it in the version 2 of the library I am currently working on. I will let you know when it is ready.
Regarding the current version, I will wait for your pull request (I am trying to motivate you learn the github way ;) )
Cheers

**Comment by fabifabi** [comment]
i hate this kind of tool  :( i have to watch it,but i am very busy for now.....i try push your library until its limit haha !

**Comment by fabifabi** [comment]
btw,what is new to v2 ???? i don't want do stuff thats' will exist soon :)

**Comment by idelvall** [comment]
it's conceptually the same, but the code is well modularized and easier to maintain and extend.
