### ISSUE TITLE
Support for DatePicker

### ISSUE THREAD

**Issue by glennswest** [brutusin/json-forms#93]
Is there a way of getting json-forms to use a datepicker?
Thinking also I might want to also use a picker for a table as well, for joined tables.

**Comment by fabifabi** [comment]
I do it using a decorator...same for color!
(u look to have same need than I :) )

**Comment by glennswest** [comment]
Its giving me pain:

Here is the upper level:

<!DOCTYPE html>
<html>
    <head>
          <title>Minidash</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="../../style.css">
        <link rel="stylesheet" type="text/css" href="../../jquery-ui-1.12.1/jquery-ui.theme.css"/>
        <link rel="stylesheet" type="text/css" href="../../jquery-ui-1.12.1/jquery-ui.structure.css"/>
        <script src="../../jQuery-2.2.4/jquery-2.2.4.min.js"></script>
        <link rel="stylesheet" href="../../jquery-ui-1.12.1/jquery-ui.css">
        <script src="../../jquery-ui-1.12.1/jquery-ui.js"></script>
        <script src="../../mddecorate.js"></script>
        <link rel="stylesheet" type="text/css" href="/brutusin-json-forms.min.css"/>
    </head>

        
        <script type="text/javascript" src="/jQuery-2.2.4/jquery-2.2.4.min.js"></script>
        <script type="text/javascript" src="/jquery-ui-1.12.1/jquery-ui.js"></script>
        <script type="text/javascript" src="/brutusin-json-forms.min.js"></script>

        <script type="text/javascript">
        $.ajaxSetup({
            cache: true
            });
        $(document).ready(function() {
          ( function($) {
             $( "#accordion" ).accordion({heightStyle: "content"});
             } ) ( jQuery );
             $.get('/api/ddb/schema?name=devices&count=1', function(data){
                    var schema = data.schema;
                    var BrutusinForms = brutusin["json-forms"];
                    BrutusinForms.addDecorator(mddecorate);
                    var bf = BrutusinForms.create(schema);
                    var container = document.getElementById('container');
                    var data = {};
                    bf.render(container, data);
                    });

         	} )
        </script>
        <body>
        <div id="accordion">
          <h3>New</h3>
          <div id="container">
          </div>
        </div>
    </body>
</html>

Here is the code that should add in the calendar:
function mddecorate(element,schema)
{
    name = element.tagName;
    switch(name){
        case "INPUT":
             gsw =  element;
             fieldname = element.placeholder.toLowerCase();
             // element.id = BrutusinForms#0_0
             if ('format' in schema){
                switch(schema.format){
                      case "date":
                            console.log(schema);
                            console.log(schema.$id);
                            console.log(element.id);
                            var theid;
                            // "input[id$=txtDatepicker]"
                            theid = '#' + element.id;
                            console.log(theid);
                            $(theid).datepicker({dateFormat: 'yy-mm-dd'});
                            break;
                      }
                }
             break;
        }
}

Console output:Navigated to http://ctl.ncc9.com:9093/view/devices/new
mddecorate.js:15 Object {type: "string", format: "date", description: "DateCreated", $id: "$.date_created"}
mddecorate.js:16 $.date_created
mddecorate.js:17 BrutusinForms#0_1
mddecorate.js:21 #BrutusinForms#0_1

Never see the datepicker. :(

What Im I missing

**Comment by glennswest** [comment]
function mddecorate(element,schema)
{
    name = element.tagName;
    switch(name){
        case "INPUT":
             gsw =  element;
             fieldname = element.placeholder.toLowerCase();
             // element.id = BrutusinForms#0_0
             if ('format' in schema){
                switch(schema.format){
                      case "date":
                            console.log(schema);
                            console.log(schema.$id);
                            console.log(element.id);
                            var theid;
                            // "input[id$=txtDatepicker]"
                            theid = '#' + element.id;
                            console.log(theid);
                            $(theid).datepicker({dateFormat: 'yy-mm-dd'});
                            break;
                      }
                }
             break;
        }
}

**Comment by glennswest** [comment]
Wow, its easy:

function mddecorate(element,schema)
{
    name = element.tagName;
    switch(name){
        case "INPUT":
             gsw =  element;
             fieldname = element.placeholder.toLowerCase();
             // element.id = BrutusinForms#0_0
             if ('format' in schema){
                switch(schema.format){
                      case "date":
                            $(element).datepicker();
                            break;
                      }
                }
             break;
        }
}

**Comment by glennswest** [comment]
For more readable version:
https://github.com/glennswest/microdash/blob/065e6983a0f8b77a90d5061959c9a216ac343bce/public/mddecorate.js

Thanks for the help.
Figured it out by reading brutusin/json-forms code, reading others code is the best way to learn.

**Comment by idelvall** [comment]
I'm late here, glad to see you figured it out
