### ISSUE TITLE
Password field

### ISSUE THREAD

**Issue by ma-hack** [brutusin/json-forms#97]
I have in the form a field that contains a password. Please, can you integrate support for the html input type option "password"? I look in the documentation but can not found anything about it.

Best regards,
Marco

**Comment by fabifabi** [comment]
use decorator ?
not so hard ;)

**Comment by ma-hack** [comment]
The generated ui is dynamic and can have multiple password fields. When i use a decorator then i must know before i get the schema which fields are the password fields. 

Have you an example how this can be work? I already look over the example: https://github.com/brutusin/json-forms/blob/master/src/js/brutusin-json-forms-bootstrap.js

**Comment by fabifabi** [comment]
can u show me your source ? or send to me ?

**Comment by ma-hack** [comment]
Sorry, that is not possible because it is a larger JavaEE project with multiple applications. The applications offer an webservice what provides the data as JSON Schema (jackson-mapper). This schema is used in the webfrontend to build a configuration ui to change the settings of this application. 

I use in the schema fields like readOnly, title, description, etc. My hope was that it is possible to set something like form:password in the schema and brutusin display the field as password field.

**Comment by idelvall** [comment]
@fabifabi maybe you can show him some examples of decorators, like the ones used for selecting colors or folders?

**Comment by fabifabi** [comment]
i never did dynamic schema.....thats' change something of the problem ? if not,i will post it tomorow,i use some plugin for color slecting (spectrum,if u know,very good one !) i need do a more easy sample.

Btw! conrgat,u are in a french magazine this month ;)

**Comment by fabifabi** [comment]
BrutusinForms.addDecorator(function (e, s)
    {
        var $this = $(e);
        if (s && s.format === "color")
            $this.attr("type", "color");
    });

with Jquery.

**Comment by idelvall** [comment]
Maybe this example is good for the question too: http://brutusin.org/json-forms/#9
The insight is to add a custom format to the strings, for example "password" and add a decorator that whenever this format is used in a string input, it change the type of the input accordingly

**Comment by idelvall** [comment]
Thanks @fabifabi!

**Comment by fabifabi** [comment]
full agree


2017-07-21 16:43 GMT+02:00 Ignacio del Valle Alles <notifications@github.com

**Comment by ma-hack** [comment]
Thank you very much for your help! That easy solution works!!

For others just put in the schema a format tag
`{"title":"Password", "description":"If authentification is needed than specifiy the password.", "format":"password", "type":"string"}`

upper the brutusin js add the decorator
`  BrutusinForms.addDecorator(function (element, s)
        {
            var $this = $(element);
            if (s && s.format === "password") {
                $this.attr("type", "password");
            }
        });`
